controllers:
    resource: ../src/Controller/
    type: attribute

livro_index:
    path: /livro
    controller: App\Controller\LivroController::index
    methods: GET

log_out:
    path: /log_out
    methods: GET